name: Daily Domain Check

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run domain check
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          DOMAIN: ${{ secrets.DOMAIN }}
          CHECK_TYPE: ${{ secrets.CHECK_TYPE }}
        run: |
          python check_domain.py
